services:
  app:
    build: .
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine-slim
    volumes:
      - type: bind
        source: nginx.default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - app
