services:
  app-1:
    build: .
    ports:
      - "3001:3000"
  
  app-2:
    build: .
    ports:
      - "3002:3000"

  nginx:
    image: nginx:alpine-slim
    volumes:
      - type: bind
        source: nginx.default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: app.crt
        target: /etc/ssl/app.crt
        read_only: true
      - type: bind
        source: app.key
        target: /etc/ssl/app.key
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-1
      - app-2
