services:
  app-1:
    build: .
    volumes:
      - type: bind
        source: unit.config.json
        target: /docker-entrypoint.d/config.json
        read_only: true
  
  app-2:
    build: .
    volumes:
      - type: bind
        source: unit.config.json
        target: /docker-entrypoint.d/config.json
        read_only: true

  nginx:
    image: nginx:alpine-slim
    volumes:
      - type: bind
        source: nginx_lb.default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: app.crt
        target: /etc/ssl/app.crt
        read_only: true
      - type: bind
        source: app.key
        target: /etc/ssl/app.key
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-1
      - app-2
